### ISSUE TITLE
Crashes when tracing `apollo-upload-client`

### ISSUE THREAD

**Issue by jaydenseric** [vercel/node-file-trace#141]
There are certain situations where `nodeFileTrace` crashes on perfectly valid modules. This critical bug is causing Vercel deployment errors for [`apollo-upload-client`](https://npm.im/apollo-upload-client) (see https://github.com/jaydenseric/apollo-upload-client/issues/211) and [`next-graphql-react`](https://npm.im/next-graphql-react)/[`graphql-react`](https://npm.im/graphql-react) users.

For example:

```js
const { nodeFileTrace } = require('@zeit/node-file-trace');
nodeFileTrace(['index.js']).then(console.log)
```

With `index.js` containing:

```js
const ReactNativeFile = require('apollo-upload-client/public/ReactNativeFile')
```

Or alternatively containing:

```js
const { ReactNativeFile } = require('apollo-upload-client')
```

`nodeFileTrace` crashes with an unhandled promise rejection:

```
(node:4082) UnhandledPromiseRejectionWarning: Error: File /[redacted]/node_modules/apollo-upload-clientpublic/ReactNativeFile does not exist.
    at Job.emitDependency (/[redacted]/node_modules/@zeit/node-file-trace/out/node-file-trace.js:261:23)
    at /[redacted]/node_modules/@zeit/node-file-trace/out/node-file-trace.js:290:36
    at async Promise.all (index 0)
    at async Job.emitDependency (/[redacted]/node_modules/@zeit/node-file-trace/out/node-file-trace.js:268:9)
    at async /[redacted]/node_modules/@zeit/node-file-trace/out/node-file-trace.js:297:21
    at async Promise.all (index 0)
    at async Job.emitDependency (/[redacted]/node_modules/@zeit/node-file-trace/out/node-file-trace.js:268:9)
    at async Promise.all (index 0)
    at async nodeFileTrace (/[redacted]/node_modules/@zeit/node-file-trace/out/node-file-trace.js:27:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4082) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems to crash when one module re-exports something from another?

For example, if you replace the contents of `index.js` with:

```js
const ReactNativeFile = require('extract-files/public/ReactNativeFile')
```

There is no crash.

**Comment by styfle** [comment]
Thanks for reporting this bug! We'll get it fixed soon 👍
